#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_management_project.Areas.Admin.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLiTiecCuoi")]
	public partial class MyDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSanh(Sanh instance);
    partial void UpdateSanh(Sanh instance);
    partial void DeleteSanh(Sanh instance);
    partial void InsertThucUong(ThucUong instance);
    partial void UpdateThucUong(ThucUong instance);
    partial void DeleteThucUong(ThucUong instance);
    partial void InsertMonAn(MonAn instance);
    partial void UpdateMonAn(MonAn instance);
    partial void DeleteMonAn(MonAn instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertPhieuDatTiec(PhieuDatTiec instance);
    partial void UpdatePhieuDatTiec(PhieuDatTiec instance);
    partial void DeletePhieuDatTiec(PhieuDatTiec instance);
    partial void InsertPhieuTheoDoiTiec(PhieuTheoDoiTiec instance);
    partial void UpdatePhieuTheoDoiTiec(PhieuTheoDoiTiec instance);
    partial void DeletePhieuTheoDoiTiec(PhieuTheoDoiTiec instance);
    partial void InsertSoDatTiec(SoDatTiec instance);
    partial void UpdateSoDatTiec(SoDatTiec instance);
    partial void DeleteSoDatTiec(SoDatTiec instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    #endregion
		
		public MyDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLiTiecCuoiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sanh> Sanhs
		{
			get
			{
				return this.GetTable<Sanh>();
			}
		}
		
		public System.Data.Linq.Table<ThucUong> ThucUongs
		{
			get
			{
				return this.GetTable<ThucUong>();
			}
		}
		
		public System.Data.Linq.Table<MonAn> MonAns
		{
			get
			{
				return this.GetTable<MonAn>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<PhieuDatTiec> PhieuDatTiecs
		{
			get
			{
				return this.GetTable<PhieuDatTiec>();
			}
		}
		
		public System.Data.Linq.Table<PhieuTheoDoiTiec> PhieuTheoDoiTiecs
		{
			get
			{
				return this.GetTable<PhieuTheoDoiTiec>();
			}
		}
		
		public System.Data.Linq.Table<SoDatTiec> SoDatTiecs
		{
			get
			{
				return this.GetTable<SoDatTiec>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sanh")]
	public partial class Sanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaS;
		
		private string _LoaiS;
		
		private string _TenS;
		
		private string _TrangThai;
		
		private string _SucChua;
		
		private System.Nullable<decimal> _Gia;
		
		private string _GhiChu;
		
		private EntitySet<PhieuDatTiec> _PhieuDatTiecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSChanging(string value);
    partial void OnMaSChanged();
    partial void OnLoaiSChanging(string value);
    partial void OnLoaiSChanged();
    partial void OnTenSChanging(string value);
    partial void OnTenSChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnSucChuaChanging(string value);
    partial void OnSucChuaChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public Sanh()
		{
			this._PhieuDatTiecs = new EntitySet<PhieuDatTiec>(new Action<PhieuDatTiec>(this.attach_PhieuDatTiecs), new Action<PhieuDatTiec>(this.detach_PhieuDatTiecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaS", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaS
		{
			get
			{
				return this._MaS;
			}
			set
			{
				if ((this._MaS != value))
				{
					this.OnMaSChanging(value);
					this.SendPropertyChanging();
					this._MaS = value;
					this.SendPropertyChanged("MaS");
					this.OnMaSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiS", DbType="NVarChar(50)")]
		public string LoaiS
		{
			get
			{
				return this._LoaiS;
			}
			set
			{
				if ((this._LoaiS != value))
				{
					this.OnLoaiSChanging(value);
					this.SendPropertyChanging();
					this._LoaiS = value;
					this.SendPropertyChanged("LoaiS");
					this.OnLoaiSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenS", DbType="NVarChar(50)")]
		public string TenS
		{
			get
			{
				return this._TenS;
			}
			set
			{
				if ((this._TenS != value))
				{
					this.OnTenSChanging(value);
					this.SendPropertyChanging();
					this._TenS = value;
					this.SendPropertyChanged("TenS");
					this.OnTenSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChua", DbType="NVarChar(50)")]
		public string SucChua
		{
			get
			{
				return this._SucChua;
			}
			set
			{
				if ((this._SucChua != value))
				{
					this.OnSucChuaChanging(value);
					this.SendPropertyChanging();
					this._SucChua = value;
					this.SendPropertyChanged("SucChua");
					this.OnSucChuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanh_PhieuDatTiec", Storage="_PhieuDatTiecs", ThisKey="MaS", OtherKey="MaS")]
		public EntitySet<PhieuDatTiec> PhieuDatTiecs
		{
			get
			{
				return this._PhieuDatTiecs;
			}
			set
			{
				this._PhieuDatTiecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDatTiecs(PhieuDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.Sanh = this;
		}
		
		private void detach_PhieuDatTiecs(PhieuDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.Sanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThucUong")]
	public partial class ThucUong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTU;
		
		private string _TenTU;
		
		private string _MoTaTU;
		
		private string _DonViTinh;
		
		private System.Nullable<int> _DonGiaTU;
		
		private EntitySet<SoDatTiec> _SoDatTiecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTUChanging(string value);
    partial void OnMaTUChanged();
    partial void OnTenTUChanging(string value);
    partial void OnTenTUChanged();
    partial void OnMoTaTUChanging(string value);
    partial void OnMoTaTUChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnDonGiaTUChanging(System.Nullable<int> value);
    partial void OnDonGiaTUChanged();
    #endregion
		
		public ThucUong()
		{
			this._SoDatTiecs = new EntitySet<SoDatTiec>(new Action<SoDatTiec>(this.attach_SoDatTiecs), new Action<SoDatTiec>(this.detach_SoDatTiecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTU", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTU
		{
			get
			{
				return this._MaTU;
			}
			set
			{
				if ((this._MaTU != value))
				{
					this.OnMaTUChanging(value);
					this.SendPropertyChanging();
					this._MaTU = value;
					this.SendPropertyChanged("MaTU");
					this.OnMaTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTU", DbType="NVarChar(50)")]
		public string TenTU
		{
			get
			{
				return this._TenTU;
			}
			set
			{
				if ((this._TenTU != value))
				{
					this.OnTenTUChanging(value);
					this.SendPropertyChanging();
					this._TenTU = value;
					this.SendPropertyChanged("TenTU");
					this.OnTenTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaTU", DbType="NVarChar(50)")]
		public string MoTaTU
		{
			get
			{
				return this._MoTaTU;
			}
			set
			{
				if ((this._MoTaTU != value))
				{
					this.OnMoTaTUChanging(value);
					this.SendPropertyChanging();
					this._MoTaTU = value;
					this.SendPropertyChanged("MoTaTU");
					this.OnMoTaTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaTU", DbType="Int")]
		public System.Nullable<int> DonGiaTU
		{
			get
			{
				return this._DonGiaTU;
			}
			set
			{
				if ((this._DonGiaTU != value))
				{
					this.OnDonGiaTUChanging(value);
					this.SendPropertyChanging();
					this._DonGiaTU = value;
					this.SendPropertyChanged("DonGiaTU");
					this.OnDonGiaTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThucUong_SoDatTiec", Storage="_SoDatTiecs", ThisKey="MaTU", OtherKey="MaTU1")]
		public EntitySet<SoDatTiec> SoDatTiecs
		{
			get
			{
				return this._SoDatTiecs;
			}
			set
			{
				this._SoDatTiecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.ThucUong = this;
		}
		
		private void detach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.ThucUong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonAn")]
	public partial class MonAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMA;
		
		private string _TenMA;
		
		private string _MoTaMA;
		
		private string _DonViTinh;
		
		private System.Nullable<int> _DonGiaMA;
		
		private string _LoaiMA;
		
		private EntitySet<SoDatTiec> _SoDatTiecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMAChanging(string value);
    partial void OnMaMAChanged();
    partial void OnTenMAChanging(string value);
    partial void OnTenMAChanged();
    partial void OnMoTaMAChanging(string value);
    partial void OnMoTaMAChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnDonGiaMAChanging(System.Nullable<int> value);
    partial void OnDonGiaMAChanged();
    partial void OnLoaiMAChanging(string value);
    partial void OnLoaiMAChanged();
    #endregion
		
		public MonAn()
		{
			this._SoDatTiecs = new EntitySet<SoDatTiec>(new Action<SoDatTiec>(this.attach_SoDatTiecs), new Action<SoDatTiec>(this.detach_SoDatTiecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMA
		{
			get
			{
				return this._MaMA;
			}
			set
			{
				if ((this._MaMA != value))
				{
					this.OnMaMAChanging(value);
					this.SendPropertyChanging();
					this._MaMA = value;
					this.SendPropertyChanged("MaMA");
					this.OnMaMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMA", DbType="NVarChar(50)")]
		public string TenMA
		{
			get
			{
				return this._TenMA;
			}
			set
			{
				if ((this._TenMA != value))
				{
					this.OnTenMAChanging(value);
					this.SendPropertyChanging();
					this._TenMA = value;
					this.SendPropertyChanged("TenMA");
					this.OnTenMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaMA", DbType="NVarChar(MAX)")]
		public string MoTaMA
		{
			get
			{
				return this._MoTaMA;
			}
			set
			{
				if ((this._MoTaMA != value))
				{
					this.OnMoTaMAChanging(value);
					this.SendPropertyChanging();
					this._MoTaMA = value;
					this.SendPropertyChanged("MoTaMA");
					this.OnMoTaMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaMA", DbType="Int")]
		public System.Nullable<int> DonGiaMA
		{
			get
			{
				return this._DonGiaMA;
			}
			set
			{
				if ((this._DonGiaMA != value))
				{
					this.OnDonGiaMAChanging(value);
					this.SendPropertyChanging();
					this._DonGiaMA = value;
					this.SendPropertyChanged("DonGiaMA");
					this.OnDonGiaMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiMA", DbType="NVarChar(50)")]
		public string LoaiMA
		{
			get
			{
				return this._LoaiMA;
			}
			set
			{
				if ((this._LoaiMA != value))
				{
					this.OnLoaiMAChanging(value);
					this.SendPropertyChanging();
					this._LoaiMA = value;
					this.SendPropertyChanged("LoaiMA");
					this.OnLoaiMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonAn_SoDatTiec", Storage="_SoDatTiecs", ThisKey="MaMA", OtherKey="MaMA1")]
		public EntitySet<SoDatTiec> SoDatTiecs
		{
			get
			{
				return this._SoDatTiecs;
			}
			set
			{
				this._SoDatTiecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.MonAn = this;
		}
		
		private void detach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.MonAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _TenDV;
		
		private string _MoTa;
		
		private System.Nullable<decimal> _DonGia;
		
		private EntitySet<SoDatTiec> _SoDatTiecs;
		
		private EntitySet<SoDatTiec> _SoDatTiecs1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public DichVu()
		{
			this._SoDatTiecs = new EntitySet<SoDatTiec>(new Action<SoDatTiec>(this.attach_SoDatTiecs), new Action<SoDatTiec>(this.detach_SoDatTiecs));
			this._SoDatTiecs1 = new EntitySet<SoDatTiec>(new Action<SoDatTiec>(this.attach_SoDatTiecs1), new Action<SoDatTiec>(this.detach_SoDatTiecs1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(50)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(50)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_SoDatTiec", Storage="_SoDatTiecs", ThisKey="MaDV", OtherKey="MaDV1")]
		public EntitySet<SoDatTiec> SoDatTiecs
		{
			get
			{
				return this._SoDatTiecs;
			}
			set
			{
				this._SoDatTiecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_SoDatTiec1", Storage="_SoDatTiecs1", ThisKey="MaDV", OtherKey="MaDV2")]
		public EntitySet<SoDatTiec> SoDatTiecs1
		{
			get
			{
				return this._SoDatTiecs1;
			}
			set
			{
				this._SoDatTiecs1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = this;
		}
		
		private void detach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = null;
		}
		
		private void attach_SoDatTiecs1(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.DichVu1 = this;
		}
		
		private void detach_SoDatTiecs1(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.DichVu1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _DiaChi;
		
		private string _SĐT;
		
		private string _CMND;
		
		private string _Email;
		
		private EntitySet<PhieuDatTiec> _PhieuDatTiecs;
		
		private EntitySet<PhieuDatTiec> _PhieuDatTiecs1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSĐTChanging(string value);
    partial void OnSĐTChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public KhachHang()
		{
			this._PhieuDatTiecs = new EntitySet<PhieuDatTiec>(new Action<PhieuDatTiec>(this.attach_PhieuDatTiecs), new Action<PhieuDatTiec>(this.detach_PhieuDatTiecs));
			this._PhieuDatTiecs1 = new EntitySet<PhieuDatTiec>(new Action<PhieuDatTiec>(this.attach_PhieuDatTiecs1), new Action<PhieuDatTiec>(this.detach_PhieuDatTiecs1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SĐT", DbType="NVarChar(50)")]
		public string SĐT
		{
			get
			{
				return this._SĐT;
			}
			set
			{
				if ((this._SĐT != value))
				{
					this.OnSĐTChanging(value);
					this.SendPropertyChanging();
					this._SĐT = value;
					this.SendPropertyChanged("SĐT");
					this.OnSĐTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuDatTiec", Storage="_PhieuDatTiecs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<PhieuDatTiec> PhieuDatTiecs
		{
			get
			{
				return this._PhieuDatTiecs;
			}
			set
			{
				this._PhieuDatTiecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuDatTiec1", Storage="_PhieuDatTiecs1", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<PhieuDatTiec> PhieuDatTiecs1
		{
			get
			{
				return this._PhieuDatTiecs1;
			}
			set
			{
				this._PhieuDatTiecs1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDatTiecs(PhieuDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_PhieuDatTiecs(PhieuDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_PhieuDatTiecs1(PhieuDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang1 = this;
		}
		
		private void detach_PhieuDatTiecs1(PhieuDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuDatTiec")]
	public partial class PhieuDatTiec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPDT;
		
		private string _MaKH;
		
		private string _MaNV;
		
		private string _MaS;
		
		private string _TenCR;
		
		private string _TenCD;
		
		private System.Nullable<System.DateTime> _NgayTC;
		
		private System.Nullable<System.TimeSpan> _GioTC;
		
		private System.Nullable<int> _SoMamDK;
		
		private System.Nullable<decimal> _SoTienCocTT;
		
		private string _GhiChu;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private EntitySet<SoDatTiec> _SoDatTiecs;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<KhachHang> _KhachHang1;
		
		private EntityRef<Sanh> _Sanh;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPDTChanging(string value);
    partial void OnMaPDTChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaSChanging(string value);
    partial void OnMaSChanged();
    partial void OnTenCRChanging(string value);
    partial void OnTenCRChanged();
    partial void OnTenCDChanging(string value);
    partial void OnTenCDChanged();
    partial void OnNgayTCChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTCChanged();
    partial void OnGioTCChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGioTCChanged();
    partial void OnSoMamDKChanging(System.Nullable<int> value);
    partial void OnSoMamDKChanged();
    partial void OnSoTienCocTTChanging(System.Nullable<decimal> value);
    partial void OnSoTienCocTTChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public PhieuDatTiec()
		{
			this._SoDatTiecs = new EntitySet<SoDatTiec>(new Action<SoDatTiec>(this.attach_SoDatTiecs), new Action<SoDatTiec>(this.detach_SoDatTiecs));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._KhachHang1 = default(EntityRef<KhachHang>);
			this._Sanh = default(EntityRef<Sanh>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPDT", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPDT
		{
			get
			{
				return this._MaPDT;
			}
			set
			{
				if ((this._MaPDT != value))
				{
					this.OnMaPDTChanging(value);
					this.SendPropertyChanging();
					this._MaPDT = value;
					this.SendPropertyChanged("MaPDT");
					this.OnMaPDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if ((this._KhachHang.HasLoadedOrAssignedValue || this._KhachHang1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaS", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string MaS
		{
			get
			{
				return this._MaS;
			}
			set
			{
				if ((this._MaS != value))
				{
					if (this._Sanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSChanging(value);
					this.SendPropertyChanging();
					this._MaS = value;
					this.SendPropertyChanged("MaS");
					this.OnMaSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCR", DbType="NVarChar(50)")]
		public string TenCR
		{
			get
			{
				return this._TenCR;
			}
			set
			{
				if ((this._TenCR != value))
				{
					this.OnTenCRChanging(value);
					this.SendPropertyChanging();
					this._TenCR = value;
					this.SendPropertyChanged("TenCR");
					this.OnTenCRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCD", DbType="NVarChar(50)")]
		public string TenCD
		{
			get
			{
				return this._TenCD;
			}
			set
			{
				if ((this._TenCD != value))
				{
					this.OnTenCDChanging(value);
					this.SendPropertyChanging();
					this._TenCD = value;
					this.SendPropertyChanged("TenCD");
					this.OnTenCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTC", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTC
		{
			get
			{
				return this._NgayTC;
			}
			set
			{
				if ((this._NgayTC != value))
				{
					this.OnNgayTCChanging(value);
					this.SendPropertyChanging();
					this._NgayTC = value;
					this.SendPropertyChanged("NgayTC");
					this.OnNgayTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioTC", DbType="Time")]
		public System.Nullable<System.TimeSpan> GioTC
		{
			get
			{
				return this._GioTC;
			}
			set
			{
				if ((this._GioTC != value))
				{
					this.OnGioTCChanging(value);
					this.SendPropertyChanging();
					this._GioTC = value;
					this.SendPropertyChanged("GioTC");
					this.OnGioTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoMamDK", DbType="Int")]
		public System.Nullable<int> SoMamDK
		{
			get
			{
				return this._SoMamDK;
			}
			set
			{
				if ((this._SoMamDK != value))
				{
					this.OnSoMamDKChanging(value);
					this.SendPropertyChanging();
					this._SoMamDK = value;
					this.SendPropertyChanged("SoMamDK");
					this.OnSoMamDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienCocTT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoTienCocTT
		{
			get
			{
				return this._SoTienCocTT;
			}
			set
			{
				if ((this._SoTienCocTT != value))
				{
					this.OnSoTienCocTTChanging(value);
					this.SendPropertyChanging();
					this._SoTienCocTT = value;
					this.SendPropertyChanged("SoTienCocTT");
					this.OnSoTienCocTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDatTiec_SoDatTiec", Storage="_SoDatTiecs", ThisKey="MaPDT", OtherKey="MaPDT")]
		public EntitySet<SoDatTiec> SoDatTiecs
		{
			get
			{
				return this._SoDatTiecs;
			}
			set
			{
				this._SoDatTiecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuDatTiec", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.PhieuDatTiecs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.PhieuDatTiecs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuDatTiec1", Storage="_KhachHang1", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang1
		{
			get
			{
				return this._KhachHang1.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang1.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang1.Entity = null;
						previousValue.PhieuDatTiecs1.Remove(this);
					}
					this._KhachHang1.Entity = value;
					if ((value != null))
					{
						value.PhieuDatTiecs1.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanh_PhieuDatTiec", Storage="_Sanh", ThisKey="MaS", OtherKey="MaS", IsForeignKey=true)]
		public Sanh Sanh
		{
			get
			{
				return this._Sanh.Entity;
			}
			set
			{
				Sanh previousValue = this._Sanh.Entity;
				if (((previousValue != value) 
							|| (this._Sanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sanh.Entity = null;
						previousValue.PhieuDatTiecs.Remove(this);
					}
					this._Sanh.Entity = value;
					if ((value != null))
					{
						value.PhieuDatTiecs.Add(this);
						this._MaS = value.MaS;
					}
					else
					{
						this._MaS = default(string);
					}
					this.SendPropertyChanged("Sanh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuDatTiec", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhieuDatTiecs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhieuDatTiecs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDatTiec = this;
		}
		
		private void detach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDatTiec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuTheoDoiTiec")]
	public partial class PhieuTheoDoiTiec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPTDT;
		
		private string _MaSDT;
		
		private string _MaNV;
		
		private string _ThongTinPS;
		
		private System.Nullable<decimal> _ChiPhiPS;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private EntityRef<SoDatTiec> _SoDatTiec;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPTDTChanging(string value);
    partial void OnMaPTDTChanged();
    partial void OnMaSDTChanging(string value);
    partial void OnMaSDTChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnThongTinPSChanging(string value);
    partial void OnThongTinPSChanged();
    partial void OnChiPhiPSChanging(System.Nullable<decimal> value);
    partial void OnChiPhiPSChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public PhieuTheoDoiTiec()
		{
			this._SoDatTiec = default(EntityRef<SoDatTiec>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPTDT", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPTDT
		{
			get
			{
				return this._MaPTDT;
			}
			set
			{
				if ((this._MaPTDT != value))
				{
					this.OnMaPTDTChanging(value);
					this.SendPropertyChanging();
					this._MaPTDT = value;
					this.SendPropertyChanged("MaPTDT");
					this.OnMaPTDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSDT", DbType="Char(6)")]
		public string MaSDT
		{
			get
			{
				return this._MaSDT;
			}
			set
			{
				if ((this._MaSDT != value))
				{
					if (this._SoDatTiec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSDTChanging(value);
					this.SendPropertyChanging();
					this._MaSDT = value;
					this.SendPropertyChanged("MaSDT");
					this.OnMaSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinPS", DbType="NVarChar(50)")]
		public string ThongTinPS
		{
			get
			{
				return this._ThongTinPS;
			}
			set
			{
				if ((this._ThongTinPS != value))
				{
					this.OnThongTinPSChanging(value);
					this.SendPropertyChanging();
					this._ThongTinPS = value;
					this.SendPropertyChanged("ThongTinPS");
					this.OnThongTinPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiPhiPS", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ChiPhiPS
		{
			get
			{
				return this._ChiPhiPS;
			}
			set
			{
				if ((this._ChiPhiPS != value))
				{
					this.OnChiPhiPSChanging(value);
					this.SendPropertyChanging();
					this._ChiPhiPS = value;
					this.SendPropertyChanged("ChiPhiPS");
					this.OnChiPhiPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SoDatTiec_PhieuTheoDoiTiec", Storage="_SoDatTiec", ThisKey="MaSDT", OtherKey="MaSDT", IsForeignKey=true)]
		public SoDatTiec SoDatTiec
		{
			get
			{
				return this._SoDatTiec.Entity;
			}
			set
			{
				SoDatTiec previousValue = this._SoDatTiec.Entity;
				if (((previousValue != value) 
							|| (this._SoDatTiec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SoDatTiec.Entity = null;
						previousValue.PhieuTheoDoiTiecs.Remove(this);
					}
					this._SoDatTiec.Entity = value;
					if ((value != null))
					{
						value.PhieuTheoDoiTiecs.Add(this);
						this._MaSDT = value.MaSDT;
					}
					else
					{
						this._MaSDT = default(string);
					}
					this.SendPropertyChanged("SoDatTiec");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuTheoDoiTiec", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhieuTheoDoiTiecs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhieuTheoDoiTiecs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoDatTiec")]
	public partial class SoDatTiec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSDT;
		
		private string _MaPDT;
		
		private string _MaNV;
		
		private string _MaMA1;
		
		private string _MaMA2;
		
		private string _MaMA3;
		
		private string _MaMA4;
		
		private string _MaMA5;
		
		private string _MaTU1;
		
		private string _MaTU2;
		
		private string _MaTU3;
		
		private string _MaDV1;
		
		private string _MaDV2;
		
		private string _MaDV3;
		
		private string _MaDV4;
		
		private string _MaDV5;
		
		private string _YeuCauKhac;
		
		private System.Nullable<decimal> _SoTienCocGT;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private EntitySet<PhieuTheoDoiTiec> _PhieuTheoDoiTiecs;
		
		private EntityRef<DichVu> _DichVu;
		
		private EntityRef<DichVu> _DichVu1;
		
		private EntityRef<MonAn> _MonAn;
		
		private EntityRef<PhieuDatTiec> _PhieuDatTiec;
		
		private EntityRef<ThucUong> _ThucUong;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSDTChanging(string value);
    partial void OnMaSDTChanged();
    partial void OnMaPDTChanging(string value);
    partial void OnMaPDTChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaMA1Changing(string value);
    partial void OnMaMA1Changed();
    partial void OnMaMA2Changing(string value);
    partial void OnMaMA2Changed();
    partial void OnMaMA3Changing(string value);
    partial void OnMaMA3Changed();
    partial void OnMaMA4Changing(string value);
    partial void OnMaMA4Changed();
    partial void OnMaMA5Changing(string value);
    partial void OnMaMA5Changed();
    partial void OnMaTU1Changing(string value);
    partial void OnMaTU1Changed();
    partial void OnMaTU2Changing(string value);
    partial void OnMaTU2Changed();
    partial void OnMaTU3Changing(string value);
    partial void OnMaTU3Changed();
    partial void OnMaDV1Changing(string value);
    partial void OnMaDV1Changed();
    partial void OnMaDV2Changing(string value);
    partial void OnMaDV2Changed();
    partial void OnMaDV3Changing(string value);
    partial void OnMaDV3Changed();
    partial void OnMaDV4Changing(string value);
    partial void OnMaDV4Changed();
    partial void OnMaDV5Changing(string value);
    partial void OnMaDV5Changed();
    partial void OnYeuCauKhacChanging(string value);
    partial void OnYeuCauKhacChanged();
    partial void OnSoTienCocGTChanging(System.Nullable<decimal> value);
    partial void OnSoTienCocGTChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public SoDatTiec()
		{
			this._PhieuTheoDoiTiecs = new EntitySet<PhieuTheoDoiTiec>(new Action<PhieuTheoDoiTiec>(this.attach_PhieuTheoDoiTiecs), new Action<PhieuTheoDoiTiec>(this.detach_PhieuTheoDoiTiecs));
			this._DichVu = default(EntityRef<DichVu>);
			this._DichVu1 = default(EntityRef<DichVu>);
			this._MonAn = default(EntityRef<MonAn>);
			this._PhieuDatTiec = default(EntityRef<PhieuDatTiec>);
			this._ThucUong = default(EntityRef<ThucUong>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSDT", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSDT
		{
			get
			{
				return this._MaSDT;
			}
			set
			{
				if ((this._MaSDT != value))
				{
					this.OnMaSDTChanging(value);
					this.SendPropertyChanging();
					this._MaSDT = value;
					this.SendPropertyChanged("MaSDT");
					this.OnMaSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPDT", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string MaPDT
		{
			get
			{
				return this._MaPDT;
			}
			set
			{
				if ((this._MaPDT != value))
				{
					if (this._PhieuDatTiec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPDTChanging(value);
					this.SendPropertyChanging();
					this._MaPDT = value;
					this.SendPropertyChanged("MaPDT");
					this.OnMaPDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA1", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaMA1
		{
			get
			{
				return this._MaMA1;
			}
			set
			{
				if ((this._MaMA1 != value))
				{
					if (this._MonAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMA1Changing(value);
					this.SendPropertyChanging();
					this._MaMA1 = value;
					this.SendPropertyChanged("MaMA1");
					this.OnMaMA1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA2", DbType="Char(5)")]
		public string MaMA2
		{
			get
			{
				return this._MaMA2;
			}
			set
			{
				if ((this._MaMA2 != value))
				{
					this.OnMaMA2Changing(value);
					this.SendPropertyChanging();
					this._MaMA2 = value;
					this.SendPropertyChanged("MaMA2");
					this.OnMaMA2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA3", DbType="Char(5)")]
		public string MaMA3
		{
			get
			{
				return this._MaMA3;
			}
			set
			{
				if ((this._MaMA3 != value))
				{
					this.OnMaMA3Changing(value);
					this.SendPropertyChanging();
					this._MaMA3 = value;
					this.SendPropertyChanged("MaMA3");
					this.OnMaMA3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA4", DbType="Char(5)")]
		public string MaMA4
		{
			get
			{
				return this._MaMA4;
			}
			set
			{
				if ((this._MaMA4 != value))
				{
					this.OnMaMA4Changing(value);
					this.SendPropertyChanging();
					this._MaMA4 = value;
					this.SendPropertyChanged("MaMA4");
					this.OnMaMA4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMA5", DbType="Char(5)")]
		public string MaMA5
		{
			get
			{
				return this._MaMA5;
			}
			set
			{
				if ((this._MaMA5 != value))
				{
					this.OnMaMA5Changing(value);
					this.SendPropertyChanging();
					this._MaMA5 = value;
					this.SendPropertyChanged("MaMA5");
					this.OnMaMA5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTU1", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaTU1
		{
			get
			{
				return this._MaTU1;
			}
			set
			{
				if ((this._MaTU1 != value))
				{
					if (this._ThucUong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTU1Changing(value);
					this.SendPropertyChanging();
					this._MaTU1 = value;
					this.SendPropertyChanged("MaTU1");
					this.OnMaTU1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTU2", DbType="Char(5)")]
		public string MaTU2
		{
			get
			{
				return this._MaTU2;
			}
			set
			{
				if ((this._MaTU2 != value))
				{
					this.OnMaTU2Changing(value);
					this.SendPropertyChanging();
					this._MaTU2 = value;
					this.SendPropertyChanged("MaTU2");
					this.OnMaTU2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTU3", DbType="Char(5)")]
		public string MaTU3
		{
			get
			{
				return this._MaTU3;
			}
			set
			{
				if ((this._MaTU3 != value))
				{
					this.OnMaTU3Changing(value);
					this.SendPropertyChanging();
					this._MaTU3 = value;
					this.SendPropertyChanged("MaTU3");
					this.OnMaTU3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV1", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaDV1
		{
			get
			{
				return this._MaDV1;
			}
			set
			{
				if ((this._MaDV1 != value))
				{
					if (this._DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDV1Changing(value);
					this.SendPropertyChanging();
					this._MaDV1 = value;
					this.SendPropertyChanged("MaDV1");
					this.OnMaDV1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV2", DbType="Char(5)")]
		public string MaDV2
		{
			get
			{
				return this._MaDV2;
			}
			set
			{
				if ((this._MaDV2 != value))
				{
					if (this._DichVu1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDV2Changing(value);
					this.SendPropertyChanging();
					this._MaDV2 = value;
					this.SendPropertyChanged("MaDV2");
					this.OnMaDV2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV3", DbType="Char(5)")]
		public string MaDV3
		{
			get
			{
				return this._MaDV3;
			}
			set
			{
				if ((this._MaDV3 != value))
				{
					this.OnMaDV3Changing(value);
					this.SendPropertyChanging();
					this._MaDV3 = value;
					this.SendPropertyChanged("MaDV3");
					this.OnMaDV3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV4", DbType="Char(5)")]
		public string MaDV4
		{
			get
			{
				return this._MaDV4;
			}
			set
			{
				if ((this._MaDV4 != value))
				{
					this.OnMaDV4Changing(value);
					this.SendPropertyChanging();
					this._MaDV4 = value;
					this.SendPropertyChanged("MaDV4");
					this.OnMaDV4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV5", DbType="Char(5)")]
		public string MaDV5
		{
			get
			{
				return this._MaDV5;
			}
			set
			{
				if ((this._MaDV5 != value))
				{
					this.OnMaDV5Changing(value);
					this.SendPropertyChanging();
					this._MaDV5 = value;
					this.SendPropertyChanged("MaDV5");
					this.OnMaDV5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauKhac", DbType="NVarChar(50)")]
		public string YeuCauKhac
		{
			get
			{
				return this._YeuCauKhac;
			}
			set
			{
				if ((this._YeuCauKhac != value))
				{
					this.OnYeuCauKhacChanging(value);
					this.SendPropertyChanging();
					this._YeuCauKhac = value;
					this.SendPropertyChanged("YeuCauKhac");
					this.OnYeuCauKhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienCocGT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoTienCocGT
		{
			get
			{
				return this._SoTienCocGT;
			}
			set
			{
				if ((this._SoTienCocGT != value))
				{
					this.OnSoTienCocGTChanging(value);
					this.SendPropertyChanging();
					this._SoTienCocGT = value;
					this.SendPropertyChanged("SoTienCocGT");
					this.OnSoTienCocGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SoDatTiec_PhieuTheoDoiTiec", Storage="_PhieuTheoDoiTiecs", ThisKey="MaSDT", OtherKey="MaSDT")]
		public EntitySet<PhieuTheoDoiTiec> PhieuTheoDoiTiecs
		{
			get
			{
				return this._PhieuTheoDoiTiecs;
			}
			set
			{
				this._PhieuTheoDoiTiecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_SoDatTiec", Storage="_DichVu", ThisKey="MaDV1", OtherKey="MaDV", IsForeignKey=true)]
		public DichVu DichVu
		{
			get
			{
				return this._DichVu.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu.Entity;
				if (((previousValue != value) 
							|| (this._DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu.Entity = null;
						previousValue.SoDatTiecs.Remove(this);
					}
					this._DichVu.Entity = value;
					if ((value != null))
					{
						value.SoDatTiecs.Add(this);
						this._MaDV1 = value.MaDV;
					}
					else
					{
						this._MaDV1 = default(string);
					}
					this.SendPropertyChanged("DichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_SoDatTiec1", Storage="_DichVu1", ThisKey="MaDV2", OtherKey="MaDV", IsForeignKey=true)]
		public DichVu DichVu1
		{
			get
			{
				return this._DichVu1.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu1.Entity;
				if (((previousValue != value) 
							|| (this._DichVu1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu1.Entity = null;
						previousValue.SoDatTiecs1.Remove(this);
					}
					this._DichVu1.Entity = value;
					if ((value != null))
					{
						value.SoDatTiecs1.Add(this);
						this._MaDV2 = value.MaDV;
					}
					else
					{
						this._MaDV2 = default(string);
					}
					this.SendPropertyChanged("DichVu1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonAn_SoDatTiec", Storage="_MonAn", ThisKey="MaMA1", OtherKey="MaMA", IsForeignKey=true)]
		public MonAn MonAn
		{
			get
			{
				return this._MonAn.Entity;
			}
			set
			{
				MonAn previousValue = this._MonAn.Entity;
				if (((previousValue != value) 
							|| (this._MonAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonAn.Entity = null;
						previousValue.SoDatTiecs.Remove(this);
					}
					this._MonAn.Entity = value;
					if ((value != null))
					{
						value.SoDatTiecs.Add(this);
						this._MaMA1 = value.MaMA;
					}
					else
					{
						this._MaMA1 = default(string);
					}
					this.SendPropertyChanged("MonAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDatTiec_SoDatTiec", Storage="_PhieuDatTiec", ThisKey="MaPDT", OtherKey="MaPDT", IsForeignKey=true)]
		public PhieuDatTiec PhieuDatTiec
		{
			get
			{
				return this._PhieuDatTiec.Entity;
			}
			set
			{
				PhieuDatTiec previousValue = this._PhieuDatTiec.Entity;
				if (((previousValue != value) 
							|| (this._PhieuDatTiec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuDatTiec.Entity = null;
						previousValue.SoDatTiecs.Remove(this);
					}
					this._PhieuDatTiec.Entity = value;
					if ((value != null))
					{
						value.SoDatTiecs.Add(this);
						this._MaPDT = value.MaPDT;
					}
					else
					{
						this._MaPDT = default(string);
					}
					this.SendPropertyChanged("PhieuDatTiec");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThucUong_SoDatTiec", Storage="_ThucUong", ThisKey="MaTU1", OtherKey="MaTU", IsForeignKey=true)]
		public ThucUong ThucUong
		{
			get
			{
				return this._ThucUong.Entity;
			}
			set
			{
				ThucUong previousValue = this._ThucUong.Entity;
				if (((previousValue != value) 
							|| (this._ThucUong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThucUong.Entity = null;
						previousValue.SoDatTiecs.Remove(this);
					}
					this._ThucUong.Entity = value;
					if ((value != null))
					{
						value.SoDatTiecs.Add(this);
						this._MaTU1 = value.MaTU;
					}
					else
					{
						this._MaTU1 = default(string);
					}
					this.SendPropertyChanged("ThucUong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_SoDatTiec", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.SoDatTiecs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.SoDatTiecs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuTheoDoiTiecs(PhieuTheoDoiTiec entity)
		{
			this.SendPropertyChanging();
			entity.SoDatTiec = this;
		}
		
		private void detach_PhieuTheoDoiTiecs(PhieuTheoDoiTiec entity)
		{
			this.SendPropertyChanging();
			entity.SoDatTiec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _SĐT;
		
		private string _CMND;
		
		private string _Email;
		
		private string _Password;
		
		private string _LoaiNV;
		
		private EntitySet<PhieuDatTiec> _PhieuDatTiecs;
		
		private EntitySet<PhieuTheoDoiTiec> _PhieuTheoDoiTiecs;
		
		private EntitySet<SoDatTiec> _SoDatTiecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSĐTChanging(string value);
    partial void OnSĐTChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnLoaiNVChanging(string value);
    partial void OnLoaiNVChanged();
    #endregion
		
		public NhanVien()
		{
			this._PhieuDatTiecs = new EntitySet<PhieuDatTiec>(new Action<PhieuDatTiec>(this.attach_PhieuDatTiecs), new Action<PhieuDatTiec>(this.detach_PhieuDatTiecs));
			this._PhieuTheoDoiTiecs = new EntitySet<PhieuTheoDoiTiec>(new Action<PhieuTheoDoiTiec>(this.attach_PhieuTheoDoiTiecs), new Action<PhieuTheoDoiTiec>(this.detach_PhieuTheoDoiTiecs));
			this._SoDatTiecs = new EntitySet<SoDatTiec>(new Action<SoDatTiec>(this.attach_SoDatTiecs), new Action<SoDatTiec>(this.detach_SoDatTiecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SĐT", DbType="VarChar(50)")]
		public string SĐT
		{
			get
			{
				return this._SĐT;
			}
			set
			{
				if ((this._SĐT != value))
				{
					this.OnSĐTChanging(value);
					this.SendPropertyChanging();
					this._SĐT = value;
					this.SendPropertyChanged("SĐT");
					this.OnSĐTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(50)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNV", DbType="NVarChar(50)")]
		public string LoaiNV
		{
			get
			{
				return this._LoaiNV;
			}
			set
			{
				if ((this._LoaiNV != value))
				{
					this.OnLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._LoaiNV = value;
					this.SendPropertyChanged("LoaiNV");
					this.OnLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuDatTiec", Storage="_PhieuDatTiecs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<PhieuDatTiec> PhieuDatTiecs
		{
			get
			{
				return this._PhieuDatTiecs;
			}
			set
			{
				this._PhieuDatTiecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuTheoDoiTiec", Storage="_PhieuTheoDoiTiecs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<PhieuTheoDoiTiec> PhieuTheoDoiTiecs
		{
			get
			{
				return this._PhieuTheoDoiTiecs;
			}
			set
			{
				this._PhieuTheoDoiTiecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_SoDatTiec", Storage="_SoDatTiecs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<SoDatTiec> SoDatTiecs
		{
			get
			{
				return this._SoDatTiecs;
			}
			set
			{
				this._SoDatTiecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDatTiecs(PhieuDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhieuDatTiecs(PhieuDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_PhieuTheoDoiTiecs(PhieuTheoDoiTiec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhieuTheoDoiTiecs(PhieuTheoDoiTiec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_SoDatTiecs(SoDatTiec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
}
#pragma warning restore 1591
